### ISSUE TITLE
Ask for pretrain model

### ISSUE THREAD

**Issue by JoyChen1998** [AHU-VRV/ECA-ShadowDetection#2]
Hi, I have retrained your method with the code you released, but cannot get the same BER 2.71 on SBU, 8.05 on CUHK either. Can you please share your pretrain model?  Thanks.

**Comment by JoyChen1998** [comment]
By the way, I calculate the BER on CUHK image results you released, only get 8.37. This result is far from the 8.05 you provided.

**Comment by AHU-VRV** [comment]
We have uploaded some pretrained models which may provide references for you. Thanks!
